# All Vagrant vagranturation is done below. The "2" in Vagrant.vagranture
# vagrantures the vagranturation version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  # Fuer vagrant script Ausgaben
  ui = Vagrant::UI::Colored.new

  default_mem = 8192
  default_cpu = 2
  default_box = 'bento/centos-7.5'

  # The most common vagranturation options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
  # VirtualBox Configuration

  machines = {
               :atlassian     => {:ip => '192.168.56.31'},
               :openshift     => {:ip => '192.168.56.101'},
               :atlcon        => {:ip => '192.168.56.110', :mem => '512', :cpu => 1},
               :idmanager     => {:ip => '192.168.56.32', :mem => '2048'},
             }

  if Vagrant.has_plugin?("vagrant-cachier")
    ui.info('Using vagrant cachier!')
    config.cache.scope       = :box
    config.cache.auto_detect = true
  else
    ui.warn('Hint:  You have not installed vagrant cachier or disabled it.')
    ui.warn('       Using it can speed up your machine provisioning.')
  end

  # Provision the VM's
  machines.each do |machine_name, machine_details|
   config.vm.define machine_name do |machine_config|
     machine_ip = machine_details[:ip]
     ui.info("Handling vm with hostname [#{machine_name.to_s}] and IP [#{machine_ip}]")
     machine_config.vm.box_check_update = false
     machine_config.vm.box = machine_details[:box] || default_box
     machine_config.vm.network :private_network, ip: machine_ip
     machine_config.vm.hostname = machine_name.to_s

     machine_config.vm.provider :virtualbox do |vb|
       reserved_mem = machine_details[:mem] || default_mem
       reserved_cpu = machine_details[:cpu] || default_cpu
       vb.name = machine_name.to_s
       vb.customize ["modifyvm", :id, "--groups", "/opendevstack"]
       vb.customize ["modifyvm", :id, "--memory", reserved_mem]
       vb.customize ["modifyvm", :id, "--cpus", reserved_cpu]
       vb.gui = false
     end #vb
   end # machine_config
  end # machines

  # machine specific folder and provisioning stuff
  config.vm.define "atlassian" do |vm_config|
    vm_config.vm.synced_folder "../..", "/ods"
  end 

  config.vm.define "openshift" do |vm_config|
    vm_config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=775,fmode=664"]
    vm_config.vm.synced_folder "./.vagrant", "/vagrant/.vagrant", mount_options: ["dmode=700,fmode=600"]
    vm_config.vm.synced_folder "../..", "/ods"
    vm_config.vm.provision "shell", path: "scripts/ansible.sh"
  end

  config.vm.define "atlcon" do |vm_config|
    vm_config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=775,fmode=664"]
    vm_config.vm.synced_folder "./.vagrant", "/vagrant/.vagrant", mount_options: ["dmode=700,fmode=600"]
    vm_config.vm.provision "shell", path: "scripts/ansible.sh"
  end

  config.vm.define "idmanager" do |vm_config|
    vm_config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=775,fmode=664"]
    vm_config.vm.synced_folder "./.vagrant", "/vagrant/.vagrant", mount_options: ["dmode=700,fmode=600"]
    vm_config.vm.provision "shell", path: "scripts/keycloak.sh"
  end

end
